apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.app }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: {{ .Values.names.app }}
  type: NodePort