apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: {{ .Values.names.kubemetric }}
    app.kubernetes.io/version: 2.3.0
  name: {{ .Values.names.kubemetric }}
  namespace: {{ .Values.namespace2 }}
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: {{ .Values.names.kubemetric }}
