apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: {{ .Values.names.kubemetric }}
    app.kubernetes.io/version: 2.3.0
  name: {{ .Values.names.kubemetric }}
  namespace: {{ .Values.namespace2 }}
