---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.names.nodeexporter }}
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: {{ .Values.names.nodeexporter }}
  ports:
  - name: {{ .Values.names.nodeexporter }}
    protocol: TCP
    port: 9100
    targetPort: 9100